require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TaxisController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Taxi. As you add validations to Taxi, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TaxisController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all taxis as @taxis" do
      taxi = Taxi.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:taxis)).to eq([taxi])
    end
  end

  describe "GET #show" do
    it "assigns the requested taxi as @taxi" do
      taxi = Taxi.create! valid_attributes
      get :show, {:id => taxi.to_param}, valid_session
      expect(assigns(:taxi)).to eq(taxi)
    end
  end

  describe "GET #new" do
    it "assigns a new taxi as @taxi" do
      get :new, {}, valid_session
      expect(assigns(:taxi)).to be_a_new(Taxi)
    end
  end

  describe "GET #edit" do
    it "assigns the requested taxi as @taxi" do
      taxi = Taxi.create! valid_attributes
      get :edit, {:id => taxi.to_param}, valid_session
      expect(assigns(:taxi)).to eq(taxi)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Taxi" do
        expect {
          post :create, {:taxi => valid_attributes}, valid_session
        }.to change(Taxi, :count).by(1)
      end

      it "assigns a newly created taxi as @taxi" do
        post :create, {:taxi => valid_attributes}, valid_session
        expect(assigns(:taxi)).to be_a(Taxi)
        expect(assigns(:taxi)).to be_persisted
      end

      it "redirects to the created taxi" do
        post :create, {:taxi => valid_attributes}, valid_session
        expect(response).to redirect_to(Taxi.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved taxi as @taxi" do
        post :create, {:taxi => invalid_attributes}, valid_session
        expect(assigns(:taxi)).to be_a_new(Taxi)
      end

      it "re-renders the 'new' template" do
        post :create, {:taxi => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested taxi" do
        taxi = Taxi.create! valid_attributes
        put :update, {:id => taxi.to_param, :taxi => new_attributes}, valid_session
        taxi.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested taxi as @taxi" do
        taxi = Taxi.create! valid_attributes
        put :update, {:id => taxi.to_param, :taxi => valid_attributes}, valid_session
        expect(assigns(:taxi)).to eq(taxi)
      end

      it "redirects to the taxi" do
        taxi = Taxi.create! valid_attributes
        put :update, {:id => taxi.to_param, :taxi => valid_attributes}, valid_session
        expect(response).to redirect_to(taxi)
      end
    end

    context "with invalid params" do
      it "assigns the taxi as @taxi" do
        taxi = Taxi.create! valid_attributes
        put :update, {:id => taxi.to_param, :taxi => invalid_attributes}, valid_session
        expect(assigns(:taxi)).to eq(taxi)
      end

      it "re-renders the 'edit' template" do
        taxi = Taxi.create! valid_attributes
        put :update, {:id => taxi.to_param, :taxi => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested taxi" do
      taxi = Taxi.create! valid_attributes
      expect {
        delete :destroy, {:id => taxi.to_param}, valid_session
      }.to change(Taxi, :count).by(-1)
    end

    it "redirects to the taxis list" do
      taxi = Taxi.create! valid_attributes
      delete :destroy, {:id => taxi.to_param}, valid_session
      expect(response).to redirect_to(taxis_url)
    end
  end

end
